name = "Create - Perfect World Post Production"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51acffc9ab5fd9040dce85c26ce3491d06a274960331c4267fb5e47c6dd5c22d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
