name = "Create - Perfect World Post Production"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5994e294a40f4637681551da5c1b8381a6e3908ef80d1ab0906659a098016b93"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
