name = "Create - Perfect World Post Production"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1b60fe1a09e147190c2d3768953a42a1f1c6151950ff23c9e51f960a8d33adb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
